travis:
  secure:
    BINSTAR_TOKEN: Mz5PfmaOOuSgpe7hzAO7EBtGEOHOE/U4sTkVhAiuwzYE32Em0HZGogdqRim5iijI8pw3JbH4y/22i6aMy0x6T4GUMAZB/+5aM6Umwt1C1L2wLGvWWUHlNNtkBR7cKkm+S4ClXJGqpR4+is6rYCPpAWOJ/YUAYqDvLPbdKbNSNwkpmmxNvLNPWnVt2rAAkF3xg8mMOWmjAEkQKxcm0dLQ5HDBiEOooeOUwSljNfEPvJ5DMLeYqS0cuF1D07wjT7G3BwYkb5EbxWF/f0OIFxcMWY75EvMVAGQ83aEmO51kCRMpZRhbCr6tZLuYpx9+0oUU1sgXxJeOlP5aFJEaZ+temW3xFNwp5ZyGS0WaJqf6Hmd2IuNMFvp3jDZ/SRy0ADAkaLRC04mz5eXOS5Z8MKZheR3k9+Z3QxShyCf29UAeismiFVFLRTwphA5iUZl7tHZlgBrqmW75bHRQ4+9yUNULJ6hKVGOYYk8Sv9Bmi3CPqUVIVLsl9IscZ9k++R7oqz3aRGcTTCgxQUyzA093JZ3cwL6KUlhxo6RTR/Yojf7OcYcYpTA3lOUbxYMOZp33gOnbYkheaK+hFun3mfN4vtaCDbo3Lu+qLTCxL2gJaFwmG37tk4ktXpHqeQEXuxPjV1lYZUTSlTxPLYVh0KAEL0BJqaWdIaeH8f8vRl0fQA8Px3Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
